#!/bin/sh
set -e
for _file in $(cat /usr/share/themes/0nyX/files) ; do
  if [ -L $_file ]; then
    rm -f "$_file"
  fi
  if [ -f $_file ]; then
    rm -f "$_file"
  fi
done
#dirs!
#find /usr/share/themes/0nyX -type d -empty -exec rmdir -pv --ignore-fail-on-non-empty {} \;
rm -f /usr/share/themes/0nyX/files
#re-enable the overlay scrollbars
sed -i '/^#0nyX$/,+1 d' /etc/environment
rm -rf /usr/share/themes/0nyX

##################
###Debian-only!###
##################
#DEBHELPER
case "$1" in
	remove|deconfigure|failed-upgrade)
		update-alternatives --remove x-cursor-theme /usr/share/icons/0nyX/cursor.theme
	;;
esac
