#!/bin/sh
set -e
#clean first
if [ -f /usr/share/themes/0nyX/files ];then
	for _file in $(cat /usr/share/themes/0nyX/files) ; do
		if [ -L $_file ]; then
			rm -fv "$_file"
		fi
		if [ -f $_file ]; then
			rm -fv "$_file"
		fi
	done
#dirs!
	rm -f /usr/share/themes/0nyX/files
#re-enable the overlay scrollbars
	sed -i '/^#0nyX$/,+1 d' /etc/environment
fi
#start here
_tmpdir="/tmp/0nyX.tmp"
if [ -d ${_tmpdir} ]; then
	rm -r ${_tmpdir}
fi
#dirs!
mkdir -p ${_tmpdir}/usr/share/themes
#downloading
cd /tmp
if type wget >/dev/null 2>&1; then
	wget -O /tmp/0nyX.zip https://codeload.github.com/sixsixfive/0nyX/zip/master
elif type curl >/dev/null 2>&1; then
	curl -o /tmp/0nyX.zip https://codeload.github.com/sixsixfive/0nyX/zip/master
fi
if [ -f ${_tmpdir}/../0nyX.zip ]; then
	if unzip -Z ${_tmpdir}/../0nyX.zip > /dev/null; then
		unzip ${_tmpdir}/../0nyX.zip -d ${_tmpdir}/usr/share/themes
		mv ${_tmpdir}/usr/share/themes/0nyX-master ${_tmpdir}/usr/share/themes/0nyX
	else
		printf "archive is corrupt - aborting!\n"
		exit 1
	fi
fi
printf "\n\n\n"
###link all themes
if [ -d ${_tmpdir}/usr/share/themes/0nyX ]; then
#icewm theme
printf "Installing IceWM theme\n"
	mkdir -p ${_tmpdir}/usr/share/icewm/themes
	#ln -sf ../../themes/0nyX/@extra/appthemes/icewm/0nyX ${_tmpdir}/usr/share/icewm/themes/0nyX
	for _f in $(find ${_tmpdir}/usr/share/themes/0nyX/@extra/appthemes/icewm/ -mindepth 1 -type d|sed 's\^.*/\\g'); do
		ln -sf ../../themes/0nyX/@extra/appthemes/icewm/$_f ${_tmpdir}/usr/share/icewm/themes/$_f
	done
#plank theme
printf "Installing Plank theme\n"
	mkdir -p ${_tmpdir}/usr/share/plank/themes
	for _f in $(find ${_tmpdir}/usr/share/themes/0nyX/@extra/appthemes/plank/ -mindepth 1 -type d|sed 's\^.*/\\g'); do
		ln -sf ../../themes/0nyX/@extra/appthemes/plank/$_f ${_tmpdir}/usr/share/plank/themes/$_f
	done
#onboard
printf "Installing Onboard theme\n"
	mkdir -p ${_tmpdir}/usr/share/onboard/themes
	for _f in $(find ${_tmpdir}/usr/share/themes/0nyX/@extra/appthemes/onboard -type f|sed 's\^.*/\\g'); do
		ln -sf ../../themes/0nyX/@extra/appthemes/onboard/$_f ${_tmpdir}/usr/share/onboard/themes/$_f
	done
#SLiM
printf "Installing SLiM theme\n"
	mkdir -p ${_tmpdir}/usr/share/slim/themes
	for _f in $(find ${_tmpdir}/usr/share/themes/0nyX/@extra/appthemes/SLiM -mindepth 1 -type d|sed 's\^.*/\\g'); do
		ln -sf ../../themes/0nyX/@extra/appthemes/SLiM/$_f ${_tmpdir}/usr/share/slim/themes/$_f
	done
#qt5ct
printf "Installing Qt5ct theme\n"
	mkdir -p ${_tmpdir}/usr/share/qt5ct/colors ${_tmpdir}/usr/share/qt5ct/qss
	ln -sf ../../themes/0nyX/@extra/appthemes/qt5ct/0nyX/colors/0nyX.conf ${_tmpdir}/usr/share/qt5ct/colors
	for _f in $(find ${_tmpdir}/usr/share/themes/0nyX/@extra/appthemes/qt5ct/0nyX/qss -type f|sed 's\^.*/\\g'); do
		ln -sf ../../themes/0nyX/@extra/appthemes/qt5ct/0nyX/qss/$_f ${_tmpdir}/usr/share/qt5ct/qss/$_f
	done
#albert(app does not support symlinks!)
printf "Installing Albert theme\n"
	mkdir -p ${_tmpdir}/usr/share/albert/themes
	cp ${_tmpdir}/usr/share/themes/0nyX/@extra/appthemes/albert/0nyX/0nyX.qss ${_tmpdir}/usr/share/albert/themes/0nyX.qss
#subthemes theme
printf "Installing HiDPI theme\n"
	ln -sf 0nyX/@extra/subthemes/0nyX-HiDPI ${_tmpdir}/usr/share/themes/0nyX-HiDPI
#icon theme
printf "Installing Icon theme\n"
	mkdir -p ${_tmpdir}/usr/share/icons
	ln -sf ../themes/0nyX/@extra/icons/0nyX ${_tmpdir}/usr/share/icons/0nyX
#WinAMP theme
printf "Installing WinAMP theme\n"
	mkdir -p ${_tmpdir}/usr/share/audacious/Skins
	ln -sf ../../themes/0nyX/@extra/appthemes/WinAMP/0nyX ${_tmpdir}/usr/share/audacious/Skins/0nyX
	mkdir -p  ${_tmpdir}/usr/share/qmmp/skins
	ln -sf ../../themes/0nyX/@extra/appthemes/WinAMP/0nyX ${_tmpdir}/usr/share/qmmp/skins/0nyX
#xfceterm theme
printf "Installing Xfce4-terminal theme\n"
	mkdir -p ${_tmpdir}/usr/share/xfce4/terminal/colorschemes
	ln -sf ../../../themes/0nyX/@extra/appthemes/xfce-terminal/0nyX.theme ${_tmpdir}/usr/share/xfce4/terminal/colorschemes/0nyX.theme
#gimp theme
printf "Installing GIMP theme\n"
	mkdir -p ${_tmpdir}/usr/share/gimp/2.0/themes/0nyX
	ln -sf ../../../../themes/0nyX/@extra/appthemes/gimp-2.0/gtkrc ${_tmpdir}/usr/share/gimp/2.0/themes/0nyX/gtkrc
#no overlay scrollbars
#	mkdir -p ${_tmpdir}/etc/X11/Xsession.d
#	printf "export GTK_OVERLAY_SCROLLING=0\nexport LIBOVERLAY_SCROLLBAR=0\n" > ${_tmpdir}/etc/X11/Xsession.d/98_0nyX
#xsession.d was a good idea however it wont work with root apps like synaptic so use /etc/environment instead
	printf '\n#0nyX\nGTK_OVERLAY_SCROLLING=0\n#0nyX\nLIBOVERLAY_SCROLLBAR=0'>> /etc/environment
##################
###Debian-only!###
##################
#chromium scrollbars
printf "Installing Chromium Browser theme\n"
	mkdir -p ${_tmpdir}/etc/chromium.d
	cat <<\EOF > ${_tmpdir}/etc/chromium.d/0nyX
export CHROMIUM_FLAGS="$CHROMIUM_FLAGS --load-extension=/usr/share/themes/0nyX/@extra/appthemes/Chromium_unpackedextension/0nyX"
EOF
#create a file list!
	find ${_tmpdir} > ${_tmpdir}/usr/share/themes/0nyX/files
	sed -i 's|^/tmp/0nyX.tmp||g' ${_tmpdir}/usr/share/themes/0nyX/files
	chmod -R 755 ${_tmpdir}
	cp -R ${_tmpdir}/* /
fi
