style"gtknotebook"{
xthickness=2
ythickness=2
GtkNotebook::tab-curvature=40
GtkNotebook::tab-overlap=2
GtkNotebook::has-backward-stepper=0
GtkNotebook::has-forward-stepper=1
GtkNotebook::has-secondary-backward-stepper=1
GtkNotebook::has-secondary-forward-stepper=0
engine"pixmap"{
image{
function=SHADOW
file="images/none.svg"
stretch=FALSE}
image{
function=BOX_GAP
file="images/shadow.svg"
detail="notebook"
border={2,2,2,2}
stretch=TRUE
gap_file="images/line.svg"
gap_border={0,0,0,0}
}
image{
function=EXTENSION
state=ACTIVE
file="images/tab-top_normal.svg"
border={4,4,26,26}
stretch=TRUE
gap_side=BOTTOM}
image{
function=EXTENSION
file="images/tab-top_active.svg"
border={4,4,26,26}
stretch=TRUE
gap_side=BOTTOM}
image{
function=EXTENSION
state=ACTIVE
file="images/tab-bottom_normal.svg"
border={4,4,26,26}
stretch=TRUE
gap_side=TOP}
image{
function=EXTENSION
file="images/tab-bottom_active.svg"
border={4,4,26,26}
stretch=TRUE
gap_side=TOP}
image{
function=EXTENSION
state=ACTIVE
file="images/tab-right_normal.svg"
border={26,26,4,4}
stretch=TRUE
gap_side=LEFT}
image{
function=EXTENSION
file="images/tab-right_active.svg"
border={26,26,4,4}
stretch=TRUE
gap_side=LEFT}
image{
function=EXTENSION
state=ACTIVE
file="images/tab-left_normal.svg"
border={26,26,4,4}
stretch=TRUE
gap_side=RIGHT}
image{
function=EXTENSION
file="images/tab-left_active.svg"
border={26,26,4,4}
stretch=TRUE
gap_side=RIGHT
}}}class"GtkNotebook"style"gtknotebook"


