#!/bin/sh
set -e
#no overlay scrollbars
#	mkdir -p etc/X11/Xsession.d
#	printf "export GTK_OVERLAY_SCROLLING=0\nexport LIBOVERLAY_SCROLLBAR=0\n" > etc/X11/Xsession.d/98_0nyX
#xsession.d was a good idea however it wont work with root apps like synaptic so use /etc/environment instead
	printf '\n#0nyX\nGTK_OVERLAY_SCROLLING=0\n#0nyX\nLIBOVERLAY_SCROLLBAR=0'>> /etc/environment
##################
###Debian-only!###
##################
#chromium scrollbars
printf "Installing Chromium Browser theme\n"
	mkdir -p etc/chromium.d
	cat <<\EOF > etc/chromium.d/0nyX
export CHROMIUM_FLAGS="$CHROMIUM_FLAGS --load-extension=/usr/share/themes/0nyX/@extra/appthemes/Chromium_unpackedextension/0nyX"
EOF
