style"menu"{
bg[NORMAL]=@base_color}
widget"*GtkWindow.gtk-combobox-popup-menu*"style"menu"
widget"*GtkMenu"style"menu"
style"menuitem"{
ythickness=3
bg[PRELIGHT]=@selected_bg_color}
widget_class"*.<GtkMenu>.<GtkMenuItem>"style"menuitem"
style"menuitem"{
fg[PRELIGHT]=@selected_fg_color}
widget_class"*.<GtkMenu>.<GtkMenuItem>.<GtkLabel>"style"menuitem"

style"menuseperator"{
xthickness=0
ythickness=1
GtkSeparatorMenuItem::horizontal-padding=0
GtkMenuItem::toggle-spacing=0
GtkWidget::wide-separators=1
GtkMenuItem::separator-height=1
GtkMenu::shadow-type=GTK_SHADOW_NONE
engine"pixmap"{
image{
function=BOX
file="../images/gtk-2.0/line.svg"
border={1,0,0,0}
stretch=TRUE}}}
widget_class"*<GtkSeparatorMenuItem>*"style"menuseperator"
