style"gtknotebook"{
xthickness=0
ythickness=0
GtkNotebook::tab-curvature=40
GtkNotebook::tab-overlap=1
GtkNotebook::has-backward-stepper=0
GtkNotebook::has-forward-stepper=1
GtkNotebook::has-secondary-backward-stepper=1
GtkNotebook::has-secondary-forward-stepper=0
engine"pixmap"{
image{
function=SHADOW
file="../images/gtk-2.0/none.svg"
stretch=FALSE}
image{
function=BOX_GAP
file="../images/gtk-2.0/shadow.svg"
detail="notebook"
border={1,1,1,1}
stretch=TRUE
gap_file="../images/gtk-2.0/line.svg"
gap_border={0,0,0,0}
}
image{
function=EXTENSION
state=ACTIVE
file="../images/gtk-2.0/tab-top_normal.svg"
border={2,2,13,13}
stretch=TRUE
gap_side=BOTTOM}
image{
function=EXTENSION
file="../images/gtk-2.0/tab-top_active.svg"
border={2,2,13,13}
stretch=TRUE
gap_side=BOTTOM}
image{
function=EXTENSION
state=ACTIVE
file="../images/gtk-2.0/tab-bottom_normal.svg"
border={2,2,13,13}
stretch=TRUE
gap_side=TOP}
image{
function=EXTENSION
file="../images/gtk-2.0/tab-bottom_active.svg"
border={2,2,13,13}
stretch=TRUE
gap_side=TOP}
image{
function=EXTENSION
state=ACTIVE
file="../images/gtk-2.0/tab-right_normal.svg"
border={13,13,2,2}
stretch=TRUE
gap_side=LEFT}
image{
function=EXTENSION
file="../images/gtk-2.0/tab-right_active.svg"
border={13,13,2,2}
stretch=TRUE
gap_side=LEFT}
image{
function=EXTENSION
state=ACTIVE
file="../images/gtk-2.0/tab-left_normal.svg"
border={13,13,2,2}
stretch=TRUE
gap_side=RIGHT}
image{
function=EXTENSION
file="../images/gtk-2.0/tab-left_active.svg"
border={13,13,2,2}
stretch=TRUE
gap_side=RIGHT
}}}class"GtkNotebook"style"gtknotebook"


